export {};
declare global {
  // Generated by dts-bundle-generator v9.5.1

  function SetOutput(fileName: string): void;
  function GetOutput(): string | undefined;
  function CloseOutput(): void;
  function SaveOutputAs(suffix: string): void;
  function SetItemSeparator(sep: string): void;
  function Eol(): void;
  function Out(s: string): void;
  function Log(...s: unknown[]): void;
  function Fail(msg: string): never;
  function Seed(seed: number): void;
  function MinMax(min: number, max: number): number;
  function Str(s: string): void;
  function Int(n: number | string): void;
  function Choice<T>(...choices: T[]): T;
  /**
   * Makes a sequence from a function.
   * @param size - sequence length
   * @param p - function that generates single element
   */
  function GenericSeq<T>(size: number, p: (i: number) => T): void;
  function GenericMatrix<T>(
    w: number,
    h: number,
    p: (x: number, y: number) => T,
  ): void;
  function SetCpp(golden: string, test?: string): void;
  function SetWatchables(...golden: string[]): void;
  function SetCppFlags(flags: string): void;
  function SetTimeout(toMs: number): void;
  function Test(): void;
  function __initializeIterator(name: string, min: number, max: number): void;
  function NextCase(): boolean;
  function ListInputFiles(dirName: string): string[];
  function ListSomeFiles(dirName: string, glob: string): string[];
  function TestSol(fileName: string): void;
  export interface ConfigType {
    verbose: boolean;
    keepInputFiles: boolean;
    watch: boolean;
  }
  const CFG: ConfigType;
  function SetConfig(cfg: Partial<ConfigType>): void;
  export interface SubmitOptions {
    openBrowser?: boolean;
  }
  function SubmitCode(
    filePath: string,
    options?: SubmitOptions,
  ): Promise<boolean>;
  function __initialize(globalObject: typeof globalThis): void;

  const CPP: string | number;
  const DIR: string | number;
  const A: string | number;
  const B: string | number;
  const C: string | number;
  const D: string | number;
  const E: string | number;
  const F: string | number;
  const G: string | number;
  const H: string | number;
  const I: string | number;
  const J: string | number;
  const K: string | number;
  const L: string | number;
  const M: string | number;
  const N: string | number;
  const O: string | number;
  const P: string | number;
  const Q: string | number;
  const R: string | number;
  const S: string | number;
  const T: string | number;
  const U: string | number;
  const V: string | number;
  const W: string | number;
  const X: string | number;
  const Y: string | number;
  const Z: string | number;
}
