export {};
declare global {
  // Generated by dts-bundle-generator v9.5.1

  function SetOutput(fileName: string): void;
  function GetOutput(): string | undefined;
  function CloseOutput(): void;
  function SaveOutputAs(suffix: string): void;
  function SetItemSeparator(sep: string): void;
  function Eol(): void;
  function Out(s: string): void;
  function Log(...s: unknown[]): void;
  function Fail(msg: string): never;
  function DirLog(o: any, depth?: number): void;
  function Seed(seed: number): void;
  function MinMax(min: number, max: number): number;
  function Shuffle<T>(arr: T[]): T[];
  function Str(s: string): void;
  function Int(n: number | string): void;
  function Choice<T>(...choices: T[]): T;
  /**
   * Makes a sequence from a function.
   * @param size - sequence length
   * @param p - function that generates single element
   */
  function GenericSeq<T>(size: number, p: (i: number) => T): void;
  /**
   * Makes a matrix from a function.
   * @param w - width of matrix
   * @param h - height of matrix
   * @param p - function that generates single element
   */
  function GenericMatrix<T>(
    w: number,
    h: number,
    p: (x: number, y: number) => T,
  ): void;
  function GenericPermutation(n: number): number[];
  function GenerateArrayWithEqualNumberOfBrackets(n: number): string[];
  function GenerateRandomString(len: number, alphabet?: string): string;
  export interface Node<T = any> {
    n: number;
    children: Node[];
    data: T;
  }
  export interface TreeGenParams {
    startNum: number;
    numNodes: number;
  }
  class TreeGenState implements TreeGenParams {
    startNum: number;
    numNodes: number;
    data?: any[];
    state?: Record<string, any>;
    nextNum?: number;
    constructor(init: TreeGenParams);
    getDepthState(key: number): any;
    getState(key: string, prevKey?: string): any;
  }
  export type NodeGen<T> = (
    parent: Node | null,
    depth: number,
    params: TreeGenState,
  ) => T | null;
  function GenTreeDepth<T>(p: NodeGen<T>, params: TreeGenParams): Node<T>;
  function GenTreeBreadth<T>(p: NodeGen<T>, params: TreeGenParams): Node<T>;
  function BinaryTreeGen<T>(p: NodeGen<T>): NodeGen<T>;
  function DfsFlattenTree(current: Node, nodes: Node[]): Node[];
  function OutputTreeChildrenBinary(root: Node): void;
  export interface Edge {
    u: number;
    v: number;
  }
  function OutputTreeEdges<T>(root: Node): void;
  function OutputTreeParents<T>(root: Node): void;
  function OutputTreeParentsCheapWay(n: number): void;
  class DiffError extends Error {}
  function SetCpp(golden: string, test?: string): void;
  function SetWatchables(...golden: string[]): void;
  function SetCppFlags(flags: string): void;
  function SetTimeout(toMs: number): void;
  function Test(
    checkerFunc?: (f1: string, f2: string, err: string, fin: string) => void,
  ): void;
  function __initializeIterator(name: string, min: number, max: number): void;
  function NextCase(): boolean;
  function ListInputFiles(dirName: string): string[];
  function ListSomeFiles(dirName: string, glob: string): string[];
  function TestSol(
    fileName: string,
    checkerFunc?: (f1: string, f2: string, err: string, fin: string) => void,
  ): void;
  function printColoredDiff(
    differences: {
      value: string;
      added?: boolean;
      removed?: boolean;
    }[],
  ): void;
  export interface ConfigType {
    verbose: boolean;
    keepInputFiles: boolean;
    watch: boolean;
  }
  const CFG: ConfigType;
  function SetConfig(cfg: Partial<ConfigType>): void;
  function GetFileAs2DArrayOfNumbers(file: string): number[][];
  function GetFileAsArrayOfStrings(file: string): string[];
  function GetFileAsArrayOfNumbers(file: string): number[];
  export type OptionalSequence =
    | {
        is_ok: 1;
        sequence: number[];
      }
    | {
        is_ok: 0;
      };
  function GetFileAsArrayOfOptionalSequences(file: string): OptionalSequence[];
  export interface SimpleTestCase {
    n: number;
    line: string;
  }
  export interface Simple2TestCase {
    n: number;
    k: number;
    line: string;
  }
  function GetFileAsArrayOfSimpleTestCases(file: string): SimpleTestCase[];
  function GetFileAsArrayOfSimple2TestCases(file: string): Simple2TestCase[];
  function PrintFile(errFileName?: string): void;
  export interface SubmitOptions {
    openBrowser?: boolean;
  }
  function SubmitCode(
    filePath: string,
    options?: SubmitOptions,
  ): Promise<boolean>;
  function __initialize(globalObject: typeof globalThis): void;

  const CPP: string | number;
  const DIR: string | number;
  const A: string | number;
  const B: string | number;
  const C: string | number;
  const D: string | number;
  const E: string | number;
  const F: string | number;
  const G: string | number;
  const H: string | number;
  const I: string | number;
  const J: string | number;
  const K: string | number;
  const L: string | number;
  const M: string | number;
  const N: string | number;
  const O: string | number;
  const P: string | number;
  const Q: string | number;
  const R: string | number;
  const S: string | number;
  const T: string | number;
  const U: string | number;
  const V: string | number;
  const W: string | number;
  const X: string | number;
  const Y: string | number;
  const Z: string | number;
}
